export const MovieTypes = {
    SET_PEOPLE_NAME: "SET_PEOPLE_NAME",
    SET_PEOPLE_DATA: "SET_PEOPLE_DATA",
    SET_FILMS_DATA: "SET_FILMS_DATA",
    SET_DESCRIPTION: "SET_DESCRIPTION",
    SET_LOADING: "SET_LOADING",
    SET_LAST_YEAR: "SET_LAST_YEAR"
}